// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAstra.Web.PlanetApi.Infrastructure.Data;

namespace ProjectAstra.Web.PlanetApi.Presentation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210105132619_ShuttleIdInPlanet")]
    partial class ShuttleIdInPlanet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjectAstra.Web.PlanetApi.Core.Models.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.Property<int>("NumberOfRobots")
                        .HasColumnType("int");

                    b.Property<int>("OrbitalSpeed")
                        .HasColumnType("int");

                    b.Property<Guid>("ShuttleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SolarSystemId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("ProjectAstra.Web.PlanetApi.Core.Models.SolarSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.Property<int>("OrbitalSpeed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SolarSystems");
                });

            modelBuilder.Entity("ProjectAstra.Web.PlanetApi.Core.Models.Planet", b =>
                {
                    b.HasOne("ProjectAstra.Web.PlanetApi.Core.Models.SolarSystem", "SolarSystem")
                        .WithMany("Planets")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
